name: Sync Repo to S3 on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  s3-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314165484819:role/github-options-practice-sync-s3-role
          aws-region: eu-west-1


      - name: Sync repository to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"
